[package]
name = "neath"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
tokio = {version = "1.47.1", features=["macros", "rt", "rt-multi-thread"]}
url = "2.5.7"
urlencoding = "2.1.3"
