[project]
name = "adapters"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "lxml>=6.0.1",
    "requests>=2.32.5",
]
